# Generated by Django 3.2.9 on 2021-12-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='creation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='file_deletion_history',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='album',
            name='length',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='size',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file_deletion_history',
            name='deletion_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='dor',
            field=models.DateField(auto_now_add=True, max_length=8, null=True),
        ),
    ]
