# Generated by Django 3.2.9 on 2021-12-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_file_phase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='phase_id',
        ),
        migrations.RemoveField(
            model_name='file_deletion_history',
            name='phase_id',
        ),
    ]
