# Generated by Django 3.2.9 on 2021-12-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20211211_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creation',
            name='current_file',
        ),
        migrations.RemoveField(
            model_name='creation',
            name='previous_file',
        ),
        migrations.AddField(
            model_name='file',
            name='creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.creation'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studio.status'),
        ),
    ]
