# Generated by Django 3.2.9 on 2021-12-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_auto_20211218_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.employee'),
        ),
    ]
