# Generated by Django 3.2.9 on 2022-02-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20220218_1321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creation',
            unique_together={('name', 'creator')},
        ),
    ]
