# Generated by Django 3.2.9 on 2021-12-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_rename_u_id_workinghour_w_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghour',
            old_name='w_id',
            new_name='e_id',
        ),
    ]
