# Generated by Django 3.2.9 on 2022-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_creation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='meetings', to='studio.User'),
        ),
    ]
