# Generated by Django 3.2.9 on 2022-03-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_alter_meeting_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_sent', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=300)),
                ('creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='studio.creation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='studio.user')),
            ],
        ),
    ]
