# Generated by Django 3.2.9 on 2021-12-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_rename_w_id_workinghour_e_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='phase_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
