# Generated by Django 3.2.9 on 2021-12-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_rename_w_id_workinghour_e_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_deletion_history',
            name='creation_id',
        ),
        migrations.RemoveField(
            model_name='file_deletion_history',
            name='phase_id',
        ),
        migrations.RemoveField(
            model_name='file_deletion_history',
            name='url',
        ),
        migrations.AddField(
            model_name='file_deletion_history',
            name='file_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='studio.file'),
            preserve_default=False,
        ),
    ]
