# Generated by Django 3.2.9 on 2021-12-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_auto_20211218_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='id',
        ),
        migrations.AddField(
            model_name='phase',
            name='phase_id',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
