# Generated by Django 3.2.9 on 2022-03-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
