# Generated by Django 3.2.9 on 2021-12-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_auto_20211221_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
