# Generated by Django 3.2.9 on 2022-04-15 09:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import studio.models
import studio.storage


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreationFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_creation_date', models.DateField(auto_now=True)),
                ('audioFile', models.FileField(storage=studio.storage.OverwriteStorage(), upload_to=studio.models.content_Audio_file_name)),
                ('creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='studio.creation')),
            ],
        ),
        migrations.CreateModel(
            name='Creations_Supervisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.creation')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='file_deletion_history',
            name='creation_id',
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=60, validators=[django.core.validators.MaxLengthValidator(60)]),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='File_Deletion_History',
        ),
        migrations.AddField(
            model_name='creation',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='creations', through='studio.Creations_Supervisors', to='studio.Employee'),
        ),
    ]
