# Generated by Django 3.2.9 on 2022-03-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creations_Supervisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.creation')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.employee')),
            ],
        ),
        migrations.AddField(
            model_name='creation',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='creations', through='studio.Creations_Supervisors', to='studio.Employee'),
        ),
    ]
