# Generated by Django 3.2.9 on 2022-03-25 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_auto_20220325_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=60, validators=[django.core.validators.MaxLengthValidator(60)]),
        ),
    ]
