# Generated by Django 3.2.9 on 2022-04-01 09:46

from django.db import migrations, models
import studio.models
import studio.storage


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_alter_note_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=studio.storage.OverwriteStorage(), upload_to=studio.models.content_file_name)),
            ],
        ),
    ]
