# Generated by Django 3.2.9 on 2022-05-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_auto_20220422_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creationfile',
            name='creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='studio.creation'),
        ),
    ]
